replicaCount: 1

image:
  repository: aminesoltan/microservice-in-python
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

env:
  VAULT_TOKEN: "37c9a1b2cf9b1d3a9d87e6be6b37d3a4"  # Replace with your actual Vault token

